name: HDC E2E Tests

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"

      - name: Install the project
        run: uv sync --locked

      - name: Ensure browsers are installed
        run: uv run playwright install --with-deps chromium-headless-shell

      - name: Run tests
        env:
          E2E_TESTING_ADMIN_PASSWORD: ${{ secrets.E2E_TESTING_ADMIN_PASSWORD }}
          E2E_TESTING_COLLABORATOR_PASSWORD: ${{ secrets.E2E_TESTING_COLLABORATOR_PASSWORD }}
        run: uv run pytest tests -vvv --screenshot=only-on-failure --base-url=https://hdc.humanbrainproject.eu

      - name: Upload screenshots with failures
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: screenshots-with-failures
          path: test-results/
          if-no-files-found: ignore
